services:
  db:
    image: mysql:5.7
    volumes:
      - .db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: my_wordpress_db_password

  wordpress:
    depends_on:
      - db
    image: wordpress:6.8-apache
    volumes:
      - ./wp-content-theme:/var/www/html/wp-content/themes/website
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
      - ./.htaccess:/var/www/html/.htaccess
    ports:
      - '${WORDPRESS_PORT}:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: my_wordpress_db_password
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('GOOGLE_API_KEY', '${GOOGLE_API_KEY}');
        define('FS_METHOD', 'direct');

volumes:
  dbvolume:
  wp-content:
