version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - .db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: my_wordpress_db_password

  wordpress:
    depends_on:
      - db
    image: wordpress:5.4.2-apache
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./theme:/var/www/html/wp-content/themes/website
      - ./uploads:/var/www/html/wp-content/uploads
      - ./.htaccess:/var/www/html/.htaccess
    ports:
      - '${PORT}:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: my_wordpress_db_password
volumes:
  dbvolume:
  wp-content:
